import { EXERCISES } from './exercises';
import { WEIGHT_EXERCISES } from './weights';
import { CATEGORIES, CATEGORY_LIST } from './categories';

export const ALL_EXERCISES = [
    ...EXERCISES,
    ...WEIGHT_EXERCISES,
];

export const EXERCISES_BY_CATEGORY = {
    [CATEGORIES.BODYWEIGHT]: EXERCISES,
    [CATEGORIES.WEIGHTS]: WEIGHT_EXERCISES,
    [CATEGORIES.CUSTOM]: [],
};

export { EXERCISES, WEIGHT_EXERCISES, CATEGORIES, CATEGORY_LIST };
